import { escapeXml } from "../utils/escape-xml";
import type { FeedItem } from "./types";

type GenerateRssInput = {
  fetchedAt: string;
  items: FeedItem[];
  selfUrl: string;
  sourceTitle: string;
  sourceUrl: string;
};

function renderItem(item: FeedItem): string {
  const lines = [
    "    <item>",
    `      <title>${escapeXml(item.title)}</title>`,
    `      <link>${escapeXml(item.link)}</link>`,
    `      <guid isPermaLink="true">${escapeXml(item.link)}</guid>`,
  ];

  if (item.desc) {
    lines.push(`      <description>${escapeXml(item.desc)}</description>`);
  }

  lines.push("    </item>");
  return lines.join("\n");
}

export function generateRss(input: GenerateRssInput): string {
  const items = input.items.map(renderItem).join("\n");

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">',
    "  <channel>",
    `    <title>${escapeXml(input.sourceTitle)}</title>`,
    `    <link>${escapeXml(input.sourceUrl)}</link>`,
    "    <description>Generated by torss</description>",
    `    <atom:link href="${escapeXml(input.selfUrl)}" rel="self" type="application/rss+xml"/>`,
    items,
    "  </channel>",
    "</rss>",
  ].join("\n");
}
