services:
  torss:
    build: .
    container_name: torss
    restart: unless-stopped
    ports:
      - "0.0.0.0:8677:8677"
    environment:
      HOST: 0.0.0.0
      PORT: 8677
      TORSS_TTL: 300
